# Presentación {-}

¿Cuál es la prevalencia de pobreza en una sociedad en cierto momento en el tiempo? ¿Por qué observamos tal nivel de pobreza? ¿Por qué algunos grupos de población o regiones son más pobres que otras? Las respuestas a estas preguntas son decisivas para cuestionar nuestro orden institucional puesto que dan pistas sobre el estado y las tendencias de cuestiones capitales como la justicia social. Una condición fundamental para responder estas preguntas es la producción de buenas medidas de pobreza. De otra manera, se genera incertidumbre en torno al dato, lo cual nubla y desvía nuestra atención, acción y juicios sobre el objetivo principal que es la erradicación de la pobreza. 

El consenso internacional es que la pobreza es multidimensional y que debería medirse considerando los aspectos sustantivos de las necesidades para la vida. Sin embargo, la respuesta sobre la prevalencia y naturaleza de la pobreza multidimensional es aún debatida e insatisfactoria. Existen varias propuestas en la literatura para el mismo problema y no es claro si hay alguna que sea superior al resto o si todas son igual de malas. Peor aún, en medición multidimensional no hay criterios estandarizados para distinguir una buena de una mala medida. Y, sin embargo, la literatura continúa produciendo medidas a gran escala. Los peligros de una mala medida son muchos. Las sociedades pueden desperdiciar recursos y tiempo cuando se basan en evidencia y datos pobres. La academia y el gobierno tienen la responsabilidad de producir medidas que sean replicables y robustas a fin de que sean útiles para el diseño e instrumentación de políticas. 

Hay varias razones teóricas y metodológicas que han impedido la producción masiva de medidas de pobreza que sean incuestionables en tanto llevan a poco incertidumbre respecto al dato que proporcionan. Primero, la existencia de varios cuerpos teóricos sobre necesidades humanas que debaten cuáles son los aspectos sustantivos para que los humanos vivan con dignidad. Segundo, aún si las discusiones teóricas tuvieran una solución satisfactoria, en la práctica hay varios obstáculos que necesitan resolverse para el desarrollo exitoso de escalas de pobreza. Este reto se manifiesta en las distintas etapas de la producción de un Índice. Para empezar, la pobreza es una invención humana, una abstracción, que requiere rastrearse usando datos multivariados para poder capturar sus aspectos sustantivos. Inevitablemente, esto resulta en un proceso de magnificación de ruido debido a que las y los investigadores tienen que levantar diversos supuestos sobre cuáles son los conjuntos relevantes de necesidades a incluir en un Índice, los umbrales para identificar privación material, los pesos que se asignan a estos indicadores para reflejar o no la importancia diferenciada de las distintas necesidades y sobre la forma en la que el grupo pobre y no pobre son identificados. Además, todos estos supuestos se ubican en el contexto de los datos disponibles, los cuáles raramente se recolectan con la idea a priori de medir pobreza. Invariablemente, estas decisiones están basadas en nuestros propios prejuicios, más o menos informados por alguna teoría. 

No existe la medición perfecta. Nuestros prejuicios y datos producen imperfección, es decir, error. La medición multidimensional de pobreza al fin es un ejercicio basado en supuestos y nuestra proximidad a una buena medida dependerá de que tan adecuados son nuestras suposiciones y de si se sostienen para los datos que estamos analizando. Pero ¿Cómo sabemos el tamaño de nuestro error? Uno de los retos principales en medición de pobreza multidimensional es cómo enfrentar el problema de error en medición: cómo definirlo y cómo cuantificarlo. 

El error es un aspecto decisivo en medición porque la incertidumbre es función del error. Nada peor que un dato que no puede replicarse porque entonces tendremos por lo menos dos datos para un mismo fenómeno. No por nada, una de las crisis actuales en ciencias sociales es la de la poca replicabilidad de resultados. Queremos cuantificar el error porque añade ruido a nuestros modelos predictivos y aumenta la incertidumbre en la estimación de la prevalencia y severidad de pobreza. En otras palabras, el ruido es variación aleatoria que nos distancia de lo que estamos interesados. En estos casos nuestra medida no es **confiable**. Además, hay otro tipo error, el sistemático. El cuál se origina por nuestros prejuicios y sesgos. Es decir, es todo aquello en lo que no estamos interesados cuando medimos pobreza, pero no nos damos cuenta porque tenemos fe en nuestros supuestos. En estos casos, nuestra medida no es válida. 

La medición de la pobreza multidimensional requiere un marco coherente y sólido para mitigar los sesgos de confirmación -leer la evidencia de forma tal que confirme nuestros prejuicios- a través del escrutinio empírico de nuestros supuestos y nuestros errores. El objetivo de este libro es proveer de un marco que ayude a investigar sistemáticamente al error en medición mediante el análisis de preguntas como: *¿Es sensible agregar nuestra lista ex ante de indicadores en un índice? ¿Hay algunos indicadores que no funcionan como se esperaba? ¿La escala ordena adecuadamente a nuestra población, es decir, de bajo a niveles altos de vida? ¿Es nuestro ordenamiento de la población consistente en distintas muestras y grupos? ¿Ayuda incluir pesos diferenciados o introduce más ruido? ¿Las dimensiones que proponemos parecen existir en los datos? ¿La división que usamos -pobre vs no pobre- lleva a grupos que tienen un perfil y significado teóricamente válido? Es decir, **¿Es nuestro índice multidimensional una medida válida y confiable?**

Este libro se enfoca en uno de los principales problemas en medición contemporánea de pobreza: *la falta de un marco sólido para examinar los supuestos en los que se basa una medida multidimensional de pobreza*. El libro propone una serie de herramientas para mitigar contra nuestros prejuicios y error en medición de pobreza. Esto no significa que el libro parte de que los investigadores están activamente tratando de producir malas escalas, es sólo un reconocimiento explícito de que siempre trabajamos con supuestos influenciados por nuestros juicios, los cuales pueden o no ser sensibles para los datos que tenemos. 

El libro se basa en **la teoría de la medición** que tiene más de 100 años de desarrollo continuo y que busca ayudar a que los investigadores no produzcan escalas que simplemente magnifican ruido. El libro trata de brindar algunos principios falsables, criterios y métodos para examinar si nuestras medidas de pobreza resultan de un minado de ruido y son irreplicables. Desafortunadamente, la investigación de pobreza ha ignorado los desarrollos en otros campos que enfrentan problemas similares y aunque en ocasiones la teoría de la medición se ha usado, su implementación es parcial, imprecisa y poco sistemática. En 2016, la Comisión del Banco Mundial [-@Bank2017], encabezada por Anthony Atkinson, puso en perspectiva los diferentes retos en medición multidimensional de pobreza y propuso 21 recomendaciones. La recomendación 4, reconoce la necesidad de validar los índices de pobreza. Sin embargo, no propone cómo hacerlo. Esto es entendible porque una de las principales dificultades en la medición contemporánea de pobreza es la ausencia de una discusión explícita sobre como checar nuestros supuestos. 

La práctica más común continúa siendo el uso de métodos ad hoc para examinar algunas propiedades (arbitrariamente definidas)
de una medida. Hasta la fecha, hay pocos ejercicios en medición multidimensional que parten de un marco estadístico claro para poner en escrutinio los supuestos de un índice. El trabajo de @Guio2012 and @Guio2017, basado en el trabajo del grupo de Pobreza y Exclusión Social y en la obra monumental de @Townsend1979, es tal vez la implementación más amplia de la teoría de la medida en medición multidimensional de pobreza. Sin embargo, los métodos y su aplicación no se han hecho accesibles a la comunidad interesada en medir pobreza. Uno de los problemas es que hay varios libros en medición de pobreza, pero no hay ninguno que se haya enfocado en el tema de evaluación empírica. La mayoría de los libros se enfocan en la producción de un índice, pero dedican pocas páginas al tema de validación. Esto, de hecho, refleja el hecho de que la medición de pobreza no ha seguido el camino de otras disciplinas que han enfrenado problemas similares. 

La medición en educación, psicometría, sociología y ciencias naturales siempre enfrentan retos de medición. A diferencia de los estudios de pobreza, estas disciplinas han tomado muy en serio el ejercicio de producción de escalas y han adoptado una serie de prácticas y principios que reducen incertidumbre sobre el atributo que buscan medir. Estas áreas se basan en el trabajo seminal de @Spearman1904 sobre correlación y variables latentes que resulto en el desarrollo de la teoría de la medida y métodos con más de 100 años de historia reflejados en: los trabajos clásicos de análisis factorial [@Thorndike1969;@Thurstone1947;@Lazardfeld1968;@Cudeck2012], el desarrollo de los principios de validez y confiabilidad [@Guttman1945,Novick1967,Novick1967,Brennan2006], el marco moderno de variables latentes [@Bartholomew1987;@Muthen2007;@Skrondal2007;@Kvalheim2012], y los manuales que muestran como estos principios y métodos constituyen en un marco robusto de medición [@Allen2001;@Brennan2006;@McDonald2013;@Streiner2015;@Michell2015]. La teoría de la medida ha sido tan ampliamente aceptada que hay llevado a la adopción de sus estándares en algunas revistas académicas para que los autores den evidencia de la calidad de sus mediciones. 

Este libro se basa en la teoría de la medida y sus métodos para ilustrar cómo bajo un marco unificado puede utilizarse para el escrutinio empírico de índices multidimensionales de pobreza. Esto es, el libro traduce en conceptos clave y principios de la teoría de la medida e ilustra su implementación usando tanto datos simulados como datos reales. Este libro está pensado para investigadores con conocimiento avanzado de pobreza y para estudiantes de posgrado. La mayoría de los ejemplos se basan en **R-software** y **Mplus** [@Muthen2012;@RCT2018]. 

El objetivo principal del libro es ayudar a investigadores, estudiantes y técnicos en el gobierno a entender la importancia de los principios de la teoría de la medida en medición multidimensional e incrementar sus habilidades técnicas para análisis empíricos de índices de pobreza. Después de estudiar el libro, los lectores podrán: 

* Encender por qué es importante trabajar con medidas falsables en la investigación de pobreza
* Identificar la diferencia entre un método de agregación y una metodología de escrutinio empírico
* Apreciar la relevancia de la teoría de la medida para examinar índices de pobreza pero también entender sus limitaciones
* Entender por qué los principios de confiabilidad y validez son una necesidad necesaria para una calidad mínima de medición
* Implementar análisis de confiabilidad y validez usando **R-software** y **Mplus**
* Interpretar los resultados de los análisis de una forma crítica
* Apreciar la importancia del principio de medición invariante y la equivalización de escalas para producir medidas comparables
* Implementar análisis básico de medición invariante y equivalización 
* Identificar los usos apropiados e inapropiados de los métodos de la teoría de la medida

El libro se organiza de la siguiente manera. El segundo capítulo introduce los vínculos entre los problemas en medición de pobreza y los principios de la teoría de la medida. El capítulo comienza con una revisión de algunos de los debates y consensos en la literatura. Después pone énfasis en los retos y supuestos que tienen lugar en la medición de pobreza y los vincula con la respuesta que la teoría de la medida a ellos. El tercer capítulo introduce, discute y traduce el concepto de confiabilidad a la medición multidimensional de pobreza. El capítulo usa datos simulados y reales para ilustrar las consecuencias de violar confiabilidad y muestra como este concepto se conecta con los axiomas en medición multidimensional. El cuarto capítulo presenta el concepto de validez y relaciones los diferentes tipos de validez con el tipo de prácticas que se hacen en medición de pobreza. El capítulo cinco se concentra en el tema de comparabilidad de medidas de pobreza. Muestra cómo el principio de medición invariante es central para hacer comparaciones válidas de grupos o periodos en el tiempo. El capítulo seis también es sobre comparabilidad, pero se enfoca en una técnica para hacer medidas comparables cuando hay discrepancias en los indicadores: equivalización de escalas. El capítulo siete se enfoca en cómo hallar la línea de pobreza usando el Método Óptimo de Bristol, el cual hace uso de modelos Lineales Generalizados. 


Este libro hubiera sido imposible sin el apoyo de...
